version: 2

sources:
  - name: raw
    description: Raw data from Telegram channels
    schema: raw
    tables:
      - name: telegram_messages
        description: Raw Telegram messages data
        columns:
          - name: id
            description: Message ID
            tests:
              - not_null
              - unique
          - name: channel
            description: Telegram channel name
            tests:
              - not_null
          - name: date
            description: Message timestamp
            tests:
              - not_null
          - name: text
            description: Message content
          - name: views
            description: Number of views
          - name: forwards
            description: Number of forwards
          - name: replies
            description: Number of replies
          - name: has_media
            description: Whether message contains media
          - name: scraped_at
            description: When data was scraped
