version: 2

models:
  - name: dim_channels
    description: Dimension table containing unique Telegram channels with aggregated statistics
    columns:
      - name: channel_key
        description: Surrogate key for the channel
        tests:
          - unique
          - not_null
      - name: channel_name
        description: Name of the Telegram channel
        tests:
          - unique
          - not_null
      - name: total_messages
        description: Total number of messages in the channel
        tests:
          - not_null
      - name: avg_views_per_message
        description: Average views per message in the channel
      - name: overall_forward_rate
        description: Overall forward rate as percentage
      - name: channel_activity_level
        description: Categorization of channel activity (high/medium/low volume)

  - name: dim_dates
    description: Dimension table containing unique dates with comprehensive date attributes
    columns:
      - name: date_key
        description: Surrogate key for the date
        tests:
          - unique
          - not_null
      - name: date_day
        description: The actual date
        tests:
          - unique
          - not_null
      - name: year
        description: Year component
        tests:
          - not_null
      - name: month
        description: Month component
        tests:
          - not_null
      - name: day
        description: Day component
        tests:
          - not_null
      - name: is_weekend
        description: Boolean indicating if date falls on weekend
      - name: day_name_short
        description: Short name of the day (Monday, Tuesday, etc.)

  - name: fct_messages
    description: Fact table containing individual Telegram messages with comprehensive metrics
    columns:
      - name: message_id
        description: Unique identifier for each message
        tests:
          - unique
          - not_null
      - name: channel_key
        description: Foreign key to dim_channels
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: Foreign key to dim_dates
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: Number of views for the message
        tests:
          - not_null
      - name: engagement_score
        description: Calculated engagement score based on views, forwards, and replies
      - name: reach_category
        description: Categorization of message reach (high/medium/low/minimal)
      - name: virality_category
        description: Categorization of message virality based on forward rate
      - name: interaction_category
        description: Categorization of message interaction based on reply rate
      - name: is_engaging_content
        description: Flag indicating if the message has meaningful engagement
