version: 2

models:
  - name: dim_channels
    description: Dimension table containing unique Telegram channels with aggregated statistics
    columns:
      - name: channel_key
        description: Surrogate key for the channel
        tests:
          - unique
          - not_null
      - name: channel_name
        description: Name of the Telegram channel
        tests:
          - unique
          - not_null
      - name: total_messages
        description: Total number of messages in the channel
        tests:
          - not_null
      - name: avg_views_per_message
        description: Average views per message in the channel
      - name: overall_forward_rate
        description: Overall forward rate as percentage
      - name: channel_activity_level
        description: Categorization of channel activity (high/medium/low volume)

  - name: dim_dates
    description: Dimension table containing unique dates with comprehensive date attributes
    columns:
      - name: date_key
        description: Surrogate key for the date
        tests:
          - unique
          - not_null
      - name: date_day
        description: The actual date
        tests:
          - unique
          - not_null
      - name: year
        description: Year component
        tests:
          - not_null
      - name: month
        description: Month component
        tests:
          - not_null
      - name: day
        description: Day component
        tests:
          - not_null
      - name: is_weekend
        description: Boolean indicating if date falls on weekend
      - name: day_name_short
        description: Short name of the day (Monday, Tuesday, etc.)

  - name: fct_messages
    description: Fact table containing individual Telegram messages with comprehensive metrics
    columns:
      - name: message_id
        description: Unique identifier for each message
        tests:
          - unique
          - not_null
      - name: channel_key
        description: Foreign key to dim_channels
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: Foreign key to dim_dates
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: Number of views for the message
        tests:
          - not_null
      - name: engagement_score
        description: Calculated engagement score based on views, forwards, and replies
      - name: reach_category
        description: Categorization of message reach (high/medium/low/minimal)
      - name: virality_category
        description: Categorization of message virality based on forward rate
      - name: interaction_category
        description: Categorization of message interaction based on reply rate
      - name: is_engaging_content
        description: Flag indicating if the message has meaningful engagement

  - name: dim_objects
    description: Dimension table containing detected objects with classification and statistics
    columns:
      - name: object_key
        description: Surrogate key for the detected object
        tests:
          - unique
          - not_null
      - name: detected_object_class
        description: Object class detected by YOLO
        tests:
          - unique
          - not_null
      - name: object_category
        description: High-level category of the object
        tests:
          - not_null
          - accepted_values:
              values:
                [
                  "people",
                  "food_drink",
                  "electronics",
                  "furniture",
                  "household_items",
                  "vehicles",
                  "sports",
                  "animals",
                  "other",
                ]
      - name: total_detections
        description: Total number of times this object was detected
        tests:
          - not_null
      - name: messages_with_object
        description: Number of messages containing this object
        tests:
          - not_null
      - name: avg_confidence
        description: Average confidence score for this object
        tests:
          - not_null
      - name: frequency_category
        description: Categorization of detection frequency
        tests:
          - not_null
          - accepted_values:
              values: ["very_common", "common", "uncommon", "rare"]

  - name: fct_image_detections
    description: Fact table containing individual object detections from images
    columns:
      - name: detection_id
        description: Unique identifier for each detection
        tests:
          - unique
          - not_null
      - name: message_id
        description: Foreign key to fct_messages
        tests:
          - not_null
          - relationships:
              to: ref('fct_messages')
              field: message_id
      - name: channel_key
        description: Foreign key to dim_channels
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: Foreign key to dim_dates
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: detected_object_class
        description: Object class detected by YOLO
        tests:
          - not_null
      - name: confidence_score
        description: Detection confidence score (0-1)
        tests:
          - not_null
      - name: confidence_level
        description: Categorized confidence level
        tests:
          - not_null
          - accepted_values:
              values: ["high", "medium", "low"]
      - name: detection_score
        description: Calculated detection score with object importance weighting
        tests:
          - not_null
      - name: bbox_area
        description: Area of the detection bounding box
        tests:
          - not_null
      - name: image_hash
        description: Hash of the processed image
        tests:
          - not_null
